# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

#
# global site settings
#
title: testdeck
email: testdeck2@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Your one stop solution for object oriented testing with Mocha, Jasmine and Jest
baseurl: ""
url: "https://testdeck.org"

#
# build settings
#
markdown: kramdown
remote_theme: testdeck/testdeck-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-remote-theme

#
# excludes
#
exclude:
  - README.md
  - attic

#
# currently disabled due to cookie regulations
#
# google custom search engine
# https://cse.google.com/cse/setup/basic?cx=010650276315653629951:v3s_qe8occu
#
#gcse:
#  id: 010650276315653629951:v3s_qe8occu
#  host: testdeck.org
